"""Master catalog of Indian government document / card types.

This is the single source of truth for every document type a citizen can
be asked to submit across any government scheme. It powers:
  - the searchable "type a letter, see matching documents" picker used when
    an official uploads a document to a citizen vault
  - validation of the doc_type sent to the upload / scan endpoints
  - the required_documents list referenced by Scheme records
"""

DOCUMENT_TYPE_CATALOG: list[dict[str, str]] = [
    {"name": 'Aadhaar Card', "category": 'Identity & Personal Documents'},
    {"name": 'Aadhaar Enrolment / Update Slip', "category": 'Identity & Personal Documents'},
    {"name": 'PAN Card', "category": 'Identity & Personal Documents'},
    {"name": 'Voter ID / EPIC', "category": 'Identity & Personal Documents'},
    {"name": 'Passport', "category": 'Identity & Personal Documents'},
    {"name": 'Driving Licence', "category": 'Identity & Personal Documents'},
    {"name": "Learner's Licence", "category": 'Identity & Personal Documents'},
    {"name": 'Ration Card', "category": 'Identity & Personal Documents'},
    {"name": 'Family ID / Family Register', "category": 'Identity & Personal Documents'},
    {"name": 'National Population Register (NPR) Details', "category": 'Identity & Personal Documents'},
    {"name": 'Government Employee ID', "category": 'Identity & Personal Documents'},
    {"name": 'Senior Citizen ID / Card', "category": 'Identity & Personal Documents'},
    {"name": 'Ex-Servicemen ID', "category": 'Identity & Personal Documents'},
    {"name": 'Freedom Fighter ID', "category": 'Identity & Personal Documents'},
    {"name": 'Birth Certificate', "category": 'Civil Registration Certificates'},
    {"name": 'Death Certificate', "category": 'Civil Registration Certificates'},
    {"name": 'Marriage Certificate', "category": 'Civil Registration Certificates'},
    {"name": 'Divorce Certificate / Order', "category": 'Civil Registration Certificates'},
    {"name": 'Adoption Certificate', "category": 'Civil Registration Certificates'},
    {"name": 'Legal Heir Certificate', "category": 'Civil Registration Certificates'},
    {"name": 'Surviving Member Certificate', "category": 'Civil Registration Certificates'},
    {"name": 'Family Member Certificate', "category": 'Civil Registration Certificates'},
    {"name": 'Succession Certificate', "category": 'Civil Registration Certificates'},
    {"name": 'Name Change Certificate', "category": 'Civil Registration Certificates'},
    {"name": 'Non-Availability of Birth Certificate', "category": 'Civil Registration Certificates'},
    {"name": 'Non-Availability of Death Certificate', "category": 'Civil Registration Certificates'},
    {"name": 'Domicile Certificate', "category": 'Residence & Citizenship'},
    {"name": 'Residence Certificate', "category": 'Residence & Citizenship'},
    {"name": 'Permanent Residence Certificate', "category": 'Residence & Citizenship'},
    {"name": 'Nativity Certificate', "category": 'Residence & Citizenship'},
    {"name": 'Nationality Certificate', "category": 'Residence & Citizenship'},
    {"name": 'Citizenship Certificate', "category": 'Residence & Citizenship'},
    {"name": 'Migration Certificate', "category": 'Residence & Citizenship'},
    {"name": 'Character Certificate', "category": 'Residence & Citizenship'},
    {"name": 'Solvency Certificate', "category": 'Residence & Citizenship'},
    {"name": 'Caste Certificate', "category": 'Caste & Social Category'},
    {"name": 'SC Certificate', "category": 'Caste & Social Category'},
    {"name": 'ST Certificate', "category": 'Caste & Social Category'},
    {"name": 'OBC Certificate', "category": 'Caste & Social Category'},
    {"name": 'OBC Non-Creamy Layer Certificate', "category": 'Caste & Social Category'},
    {"name": 'EWS Certificate', "category": 'Caste & Social Category'},
    {"name": 'Scheduled Tribe Validity Certificate', "category": 'Caste & Social Category'},
    {"name": 'Caste Validity Certificate', "category": 'Caste & Social Category'},
    {"name": 'Tribal Certificate', "category": 'Caste & Social Category'},
    {"name": 'Income Certificate', "category": 'Income & Economic Status'},
    {"name": 'BPL Certificate', "category": 'Income & Economic Status'},
    {"name": 'Economically Weaker Family Certificate', "category": 'Income & Economic Status'},
    {"name": 'Family Income Certificate', "category": 'Income & Economic Status'},
    {"name": 'Unemployment Certificate', "category": 'Income & Economic Status'},
    {"name": 'UDID Card', "category": 'Disability & Special Assistance'},
    {"name": 'Disability Certificate', "category": 'Disability & Special Assistance'},
    {"name": 'Disability Pension Document', "category": 'Disability & Special Assistance'},
    {"name": 'Rehabilitation Certificate', "category": 'Disability & Special Assistance'},
    {"name": 'Disability Assessment Document', "category": 'Disability & Special Assistance'},
    {"name": 'Caregiver Certificate', "category": 'Disability & Special Assistance'},
    {"name": 'Ayushman Bharat PM-JAY Card', "category": 'Health & Healthcare'},
    {"name": 'ABHA ID', "category": 'Health & Healthcare'},
    {"name": 'Health Insurance Card', "category": 'Health & Healthcare'},
    {"name": 'Government Health Scheme Card', "category": 'Health & Healthcare'},
    {"name": 'CGHS Card', "category": 'Health & Healthcare'},
    {"name": 'ECHS Card', "category": 'Health & Healthcare'},
    {"name": 'Health Certificate', "category": 'Health & Healthcare'},
    {"name": 'Medical Fitness Certificate', "category": 'Health & Healthcare'},
    {"name": 'Vaccination Certificate', "category": 'Health & Healthcare'},
    {"name": 'Immunization Record', "category": 'Health & Healthcare'},
    {"name": 'Maternal Health Record', "category": 'Health & Healthcare'},
    {"name": 'Child Health Record', "category": 'Health & Healthcare'},
    {"name": 'Organ Donation Registration', "category": 'Health & Healthcare'},
    {"name": 'Blood Donor Registration', "category": 'Health & Healthcare'},
    {"name": 'NFSA Ration Card', "category": 'Food & Ration'},
    {"name": 'Priority Household (PHH) Card', "category": 'Food & Ration'},
    {"name": 'Antyodaya Anna Yojana (AAY) Card', "category": 'Food & Ration'},
    {"name": 'One Nation One Ration Card', "category": 'Food & Ration'},
    {"name": 'Ration Card Member Details', "category": 'Food & Ration'},
    {"name": 'Ration Card Transfer Certificate', "category": 'Food & Ration'},
    {"name": 'Ration Card Address Change Certificate', "category": 'Food & Ration'},
    {"name": 'Ration Card Surrender Certificate', "category": 'Food & Ration'},
    {"name": 'Farmer ID', "category": 'Farmer & Agriculture'},
    {"name": 'Farmer Registration Certificate', "category": 'Farmer & Agriculture'},
    {"name": 'PM-KISAN Registration', "category": 'Farmer & Agriculture'},
    {"name": 'Kisan Credit Card (KCC)', "category": 'Farmer & Agriculture'},
    {"name": 'Soil Health Card', "category": 'Farmer & Agriculture'},
    {"name": 'Crop Registration Certificate', "category": 'Farmer & Agriculture'},
    {"name": 'Crop Insurance Document', "category": 'Farmer & Agriculture'},
    {"name": 'PM Fasal Bima Yojana Document', "category": 'Farmer & Agriculture'},
    {"name": 'Land Possession Certificate', "category": 'Farmer & Agriculture'},
    {"name": 'Land Conversion Certificate', "category": 'Farmer & Agriculture'},
    {"name": 'Agricultural Subsidy Document', "category": 'Farmer & Agriculture'},
    {"name": 'Farmer Pension Document', "category": 'Farmer & Agriculture'},
    {"name": 'Agricultural Equipment Subsidy Document', "category": 'Farmer & Agriculture'},
    {"name": 'Seed / Fertilizer Subsidy Document', "category": 'Farmer & Agriculture'},
    {"name": 'RTC / Pahani', "category": 'Land & Property'},
    {"name": 'Khata Certificate', "category": 'Land & Property'},
    {"name": 'Khata Extract', "category": 'Land & Property'},
    {"name": 'Encumbrance Certificate', "category": 'Land & Property'},
    {"name": 'Sale Deed', "category": 'Land & Property'},
    {"name": 'Property Registration Certificate', "category": 'Land & Property'},
    {"name": 'Mutation Certificate', "category": 'Land & Property'},
    {"name": 'Land Ownership Certificate', "category": 'Land & Property'},
    {"name": 'Survey Document', "category": 'Land & Property'},
    {"name": 'Property Tax Document', "category": 'Land & Property'},
    {"name": 'Building Plan Approval', "category": 'Land & Property'},
    {"name": 'Building Licence', "category": 'Land & Property'},
    {"name": 'Occupancy Certificate', "category": 'Land & Property'},
    {"name": 'Completion Certificate', "category": 'Land & Property'},
    {"name": 'Construction Permission', "category": 'Land & Property'},
    {"name": 'Property Valuation Certificate', "category": 'Land & Property'},
    {"name": 'Student ID', "category": 'Education & Students'},
    {"name": 'Bonafide Certificate', "category": 'Education & Students'},
    {"name": 'Transfer Certificate', "category": 'Education & Students'},
    {"name": 'Study Certificate', "category": 'Education & Students'},
    {"name": 'Marks Card', "category": 'Education & Students'},
    {"name": 'Degree Certificate', "category": 'Education & Students'},
    {"name": 'Diploma Certificate', "category": 'Education & Students'},
    {"name": 'Provisional Certificate', "category": 'Education & Students'},
    {"name": 'Scholarship Certificate', "category": 'Education & Students'},
    {"name": 'Hostel Certificate', "category": 'Education & Students'},
    {"name": 'Fee Receipt', "category": 'Education & Students'},
    {"name": 'National Scholarship Portal Registration', "category": 'Education & Students'},
    {"name": 'State Scholarship Portal Registration', "category": 'Education & Students'},
    {"name": 'Academic Bank of Credits (ABC) ID', "category": 'Education & Students'},
    {"name": 'APAAR ID', "category": 'Education & Students'},
    {"name": 'e-Shram Card', "category": 'Employment & Labour'},
    {"name": 'Labour Card', "category": 'Employment & Labour'},
    {"name": 'BOCW Card', "category": 'Employment & Labour'},
    {"name": 'MGNREGA Job Card', "category": 'Employment & Labour'},
    {"name": 'Employment Exchange Registration', "category": 'Employment & Labour'},
    {"name": 'UAN', "category": 'Employment & Labour'},
    {"name": 'EPFO Document', "category": 'Employment & Labour'},
    {"name": 'ESIC Card', "category": 'Employment & Labour'},
    {"name": 'Service Certificate', "category": 'Employment & Labour'},
    {"name": 'Experience Certificate', "category": 'Employment & Labour'},
    {"name": 'Skill Certificate', "category": 'Employment & Labour'},
    {"name": 'Apprenticeship Document', "category": 'Employment & Labour'},
    {"name": 'Unemployment Registration', "category": 'Employment & Labour'},
    {"name": 'Old Age Pension Document', "category": 'Pension & Social Security'},
    {"name": 'Widow Pension Document', "category": 'Pension & Social Security'},
    {"name": 'National Social Assistance Programme Document', "category": 'Pension & Social Security'},
    {"name": 'Pension Payment Order (PPO)', "category": 'Pension & Social Security'},
    {"name": 'Life Certificate', "category": 'Pension & Social Security'},
    {"name": 'Jeevan Pramaan', "category": 'Pension & Social Security'},
    {"name": 'Family Pension Document', "category": 'Pension & Social Security'},
    {"name": 'Government Employee Pension Document', "category": 'Pension & Social Security'},
    {"name": 'EPFO Pension Document', "category": 'Pension & Social Security'},
    {"name": 'Atal Pension Yojana Document', "category": 'Pension & Social Security'},
    {"name": 'Child Aadhaar', "category": 'Women & Child Welfare'},
    {"name": 'Anganwadi Registration', "category": 'Women & Child Welfare'},
    {"name": 'Maternity Registration', "category": 'Women & Child Welfare'},
    {"name": 'PM Matru Vandana Yojana Document', "category": 'Women & Child Welfare'},
    {"name": 'Sukanya Samriddhi Document', "category": 'Women & Child Welfare'},
    {"name": 'Women SHG Registration', "category": 'Women & Child Welfare'},
    {"name": 'Self Help Group Document', "category": 'Women & Child Welfare'},
    {"name": 'Girl Child Scholarship Document', "category": 'Women & Child Welfare'},
    {"name": 'Child Scholarship Document', "category": 'Women & Child Welfare'},
    {"name": 'Child Protection Document', "category": 'Women & Child Welfare'},
    {"name": 'Jan Dhan Account', "category": 'Financial & Banking'},
    {"name": 'Bank Account Details', "category": 'Financial & Banking'},
    {"name": 'Bank Passbook', "category": 'Financial & Banking'},
    {"name": 'DBT Registration', "category": 'Financial & Banking'},
    {"name": 'PMJJBY Document', "category": 'Financial & Banking'},
    {"name": 'PMSBY Document', "category": 'Financial & Banking'},
    {"name": 'Udyam Registration Certificate', "category": 'Business & MSME'},
    {"name": 'MSME Certificate', "category": 'Business & MSME'},
    {"name": 'GST Registration Certificate', "category": 'Business & MSME'},
    {"name": 'GSTIN', "category": 'Business & MSME'},
    {"name": 'Shop & Establishment Registration', "category": 'Business & MSME'},
    {"name": 'Trade Licence', "category": 'Business & MSME'},
    {"name": 'FSSAI Licence', "category": 'Business & MSME'},
    {"name": 'Startup India Registration', "category": 'Business & MSME'},
    {"name": 'Startup Recognition Certificate', "category": 'Business & MSME'},
    {"name": 'Professional Tax Registration', "category": 'Business & MSME'},
    {"name": 'Business PAN', "category": 'Business & MSME'},
    {"name": 'Company Registration Certificate', "category": 'Business & MSME'},
    {"name": 'Partnership Registration', "category": 'Business & MSME'},
    {"name": 'LLP Registration', "category": 'Business & MSME'},
    {"name": 'Import Export Code (IEC)', "category": 'Business & MSME'},
    {"name": 'Factory Licence', "category": 'Business & MSME'},
    {"name": 'Fire Safety Certificate', "category": 'Business & MSME'},
    {"name": 'Vehicle Registration Certificate (RC)', "category": 'Transport & Vehicles'},
    {"name": 'Vehicle Ownership Certificate', "category": 'Transport & Vehicles'},
    {"name": 'Fitness Certificate', "category": 'Transport & Vehicles'},
    {"name": 'Pollution Under Control (PUC) Certificate', "category": 'Transport & Vehicles'},
    {"name": 'Vehicle Insurance', "category": 'Transport & Vehicles'},
    {"name": 'National Permit', "category": 'Transport & Vehicles'},
    {"name": 'State Permit', "category": 'Transport & Vehicles'},
    {"name": 'Commercial Vehicle Permit', "category": 'Transport & Vehicles'},
    {"name": 'Road Tax Document', "category": 'Transport & Vehicles'},
    {"name": 'Vehicle Transfer Document', "category": 'Transport & Vehicles'},
    {"name": 'Vehicle NOC', "category": 'Transport & Vehicles'},
    {"name": 'New Voter Registration', "category": 'Electoral Services'},
    {"name": 'Voter Address Change Document', "category": 'Electoral Services'},
    {"name": 'Voter Correction Document', "category": 'Electoral Services'},
    {"name": 'Voter Deletion Document', "category": 'Electoral Services'},
    {"name": 'Electoral Roll Details', "category": 'Electoral Services'},
    {"name": 'Voter Transfer Document', "category": 'Electoral Services'},
    {"name": 'Overseas Elector Registration', "category": 'Electoral Services'},
    {"name": 'PMAY Beneficiary Document', "category": 'Housing & Welfare Schemes'},
    {"name": 'Housing Eligibility Certificate', "category": 'Housing & Welfare Schemes'},
    {"name": 'Housing Subsidy Document', "category": 'Housing & Welfare Schemes'},
    {"name": 'Rural Housing Document', "category": 'Housing & Welfare Schemes'},
    {"name": 'Urban Housing Document', "category": 'Housing & Welfare Schemes'},
    {"name": 'Construction Assistance Document', "category": 'Housing & Welfare Schemes'},
    {"name": 'Toilet / Sanitation Scheme Document', "category": 'Housing & Welfare Schemes'},
    {"name": 'Drinking Water Scheme Document', "category": 'Housing & Welfare Schemes'},
    {"name": 'LPG Subsidy Document', "category": 'Housing & Welfare Schemes'},
    {"name": 'Electricity Subsidy Document', "category": 'Housing & Welfare Schemes'},
    {"name": 'Electricity Connection Document', "category": 'Electricity, Water & Utilities'},
    {"name": 'Electricity Consumer ID', "category": 'Electricity, Water & Utilities'},
    {"name": 'New Electricity Connection Document', "category": 'Electricity, Water & Utilities'},
    {"name": 'Water Connection Document', "category": 'Electricity, Water & Utilities'},
    {"name": 'Water Consumer ID', "category": 'Electricity, Water & Utilities'},
    {"name": 'LPG Connection Document', "category": 'Electricity, Water & Utilities'},
    {"name": 'LPG Consumer ID', "category": 'Electricity, Water & Utilities'},
    {"name": 'Solar Subsidy Document', "category": 'Electricity, Water & Utilities'},
    {"name": 'Rooftop Solar Registration', "category": 'Electricity, Water & Utilities'},
    {"name": 'Discharge Certificate', "category": 'Defence & Ex-Servicemen'},
    {"name": 'Defence Pension Payment Order', "category": 'Defence & Ex-Servicemen'},
    {"name": 'CSD Document', "category": 'Defence & Ex-Servicemen'},
    {"name": 'Widow / Dependent Certificate', "category": 'Defence & Ex-Servicemen'},
    {"name": 'War Disability Certificate', "category": 'Defence & Ex-Servicemen'},
    {"name": 'Police Clearance Certificate', "category": 'Police & Legal Services'},
    {"name": 'FIR Copy', "category": 'Police & Legal Services'},
    {"name": 'Lost Document Report', "category": 'Police & Legal Services'},
    {"name": 'Tenant Verification Certificate', "category": 'Police & Legal Services'},
    {"name": 'Passport Verification Certificate', "category": 'Police & Legal Services'},
    {"name": 'Legal Aid Document', "category": 'Police & Legal Services'},
    {"name": 'Victim Compensation Document', "category": 'Police & Legal Services'},
    {"name": 'Widow Certificate', "category": 'Certificates for Specific Circumstances'},
    {"name": 'Unmarried Certificate', "category": 'Certificates for Specific Circumstances'},
    {"name": 'Divorcee Certificate', "category": 'Certificates for Specific Circumstances'},
    {"name": 'Orphan Certificate', "category": 'Certificates for Specific Circumstances'},
    {"name": 'Destitute Certificate', "category": 'Certificates for Specific Circumstances'},
    {"name": 'Homeless Certificate', "category": 'Certificates for Specific Circumstances'},
    {"name": 'Dependency Certificate', "category": 'Certificates for Specific Circumstances'},
    {"name": 'Freedom Fighter Certificate', "category": 'Certificates for Specific Circumstances'},
    {"name": 'Single Woman Certificate', "category": 'Certificates for Specific Circumstances'},
    {"name": 'Transgender Certificate', "category": 'Certificates for Specific Circumstances'},
    {"name": 'Third Gender Certificate', "category": 'Certificates for Specific Circumstances'},

    # ---- Added from SugamSeva_Master_Schemes_Documents_ProblemCategories.xlsx
    # ("Documents Master" sheet). These are document types referenced as
    # candidate/eligibility documents by one or more schemes in the master
    # scheme catalog (see app.scheme_master_data) but were missing here,
    # which meant an official could never actually select/verify them for a
    # citizen in Add User - so a citizen could never be marked eligible for
    # any scheme that required one of them.
    {"name": 'Aadhaar', "category": 'Government Scheme Application Documents'},
    {"name": 'Aadhaar Enrolment/Update', "category": 'Identity & Personal Documents'},
    {"name": 'Aadhaar-bank linking', "category": 'Financial & Banking'},
    {"name": 'Aadhaar-linked student details', "category": 'Education & Students'},
    {"name": 'Bank Account', "category": 'Financial & Banking'},
    {"name": 'Bank Account/IFSC details', "category": 'Government Scheme Application Documents'},
    {"name": 'Blood Donor registration', "category": 'Health & Healthcare'},
    {"name": 'Caste Certificate for scholarship', "category": 'Education & Students'},
    {"name": 'Child Health Records', "category": 'Health & Healthcare'},
    {"name": 'Child Protection documents', "category": 'Women & Child Welfare'},
    {"name": 'Child Scholarship documents', "category": 'Women & Child Welfare'},
    {"name": 'Crop Insurance documents', "category": 'Farmer & Agriculture'},
    {"name": 'Crop Registration', "category": 'Farmer & Agriculture'},
    {"name": 'Disability Certificate for scholarship', "category": 'Education & Students'},
    {"name": 'Disability Pension documents', "category": 'Pension & Social Security'},
    {"name": 'Divorce Certificate/Order', "category": 'Civil Registration Certificates'},
    {"name": 'Drinking Water Scheme documents', "category": 'Electricity, Water & Utilities'},
    {"name": 'EPFO Pension documents', "category": 'Pension & Social Security'},
    {"name": 'EPFO documents', "category": 'Employment & Labour'},
    {"name": 'Electricity Connection Documents', "category": 'Electricity, Water & Utilities'},
    {"name": 'Electricity Subsidy Documents', "category": 'Electricity, Water & Utilities'},
    {"name": 'Electricity Subsidy documents', "category": 'Housing & Welfare Schemes'},
    {"name": 'Family Pension documents', "category": 'Pension & Social Security'},
    {"name": 'Farmer Pension documents', "category": 'Farmer & Agriculture'},
    {"name": 'Farmer Registration', "category": 'Farmer & Agriculture'},
    {"name": 'Girl Child Scholarship documents', "category": 'Women & Child Welfare'},
    {"name": 'Government Employee Pension documents', "category": 'Pension & Social Security'},
    {"name": 'Immunization Records', "category": 'Health & Healthcare'},
    {"name": 'Income Certificate for scholarship', "category": 'Education & Students'},
    {"name": 'Irrigation-related documents', "category": 'Farmer & Agriculture'},
    {"name": 'Job Card', "category": 'Government Scheme Application Documents'},
    {"name": 'LPG Connection', "category": 'Electricity, Water & Utilities'},
    {"name": 'LPG Subsidy documents', "category": 'Electricity, Water & Utilities'},
    {"name": 'Maternal Health Records', "category": 'Health & Healthcare'},
    {"name": 'Mobile Number', "category": 'Government Scheme Application Documents'},
    {"name": 'National Scholarship Portal registration', "category": 'Education & Students'},
    {"name": 'New Electricity Connection', "category": 'Electricity, Water & Utilities'},
    {"name": 'Old Age Pension documents', "category": 'Pension & Social Security'},
    {"name": 'Organ Donation registration', "category": 'Health & Healthcare'},
    {"name": 'Pollution Under Control (PUC)', "category": 'Transport & Vehicles'},
    {"name": 'Solar Subsidy documents', "category": 'Electricity, Water & Utilities'},
    {"name": 'Water Connection Documents', "category": 'Electricity, Water & Utilities'},
    {"name": 'Widow Pension documents', "category": 'Women & Child Welfare'},
    {"name": 'Women SHG registration', "category": 'Women & Child Welfare'},
]

# Fast O(1) membership check for validating an uploaded doc_type against
# the master catalog above.
VALID_DOCUMENT_TYPES: set[str] = {d["name"] for d in DOCUMENT_TYPE_CATALOG}