// Master classification layer for citizen-reported civic problems.
// Mirrors the sector coverage of national scheme platforms (e.g. myScheme)
// so problems can later be matched against eligible government schemes.
// "Others" is always last and is the fallback when nothing else fits.
export const PROBLEM_CATEGORIES: string[] = [
  "🌾 Agriculture & Farming",
  "🐄 Animal Husbandry & Dairy",
  "🐟 Fisheries",
  "🌳 Forestry & Forest Communities",
  "🏡 Rural Development",
  "🏙️ Urban Development",
  "💼 Employment & Jobs",
  "🛠️ Skill Development & Training",
  "🏭 Labour & Workers",
  "💰 Banking & Financial Inclusion",
  "🏦 Loans & Credit",
  "🛡️ Insurance & Social Security",
  "💵 Pensions & Financial Assistance",
  "🏥 Healthcare & Medical Services",
  "🧑‍🍼 Maternal & Reproductive Health",
  "👶 Children & Child Welfare",
  "👩 Women Empowerment & Welfare",
  "👴 Senior Citizens",
  "♿ Persons with Disabilities",
  "🧑‍🤝‍🧑 SC/ST/OBC & Socially Disadvantaged Groups",
  "🕌 Minority Welfare",
  "🏠 Housing & Shelter",
  "🚰 Water Supply",
  "🚽 Sanitation & Waste Management",
  "⚡ Electricity & Energy",
  "🔥 Cooking Fuel & LPG",
  "🌱 Environment & Climate",
  "🌪️ Disaster Management & Relief",
  "🌾 Drought & Water Scarcity",
  "🚨 Emergency & Public Safety",
  "⚖️ Law, Justice & Legal Aid",
  "📢 Government Grievances & Complaints",
  "🪪 Identity & Citizen Documents",
  "📜 Certificates & Registrations",
  "🗳️ Elections & Democratic Services",
  "🛂 Citizenship & Passport Services",
  "🏞️ Land & Land Records",
  "🏘️ Property & Registration",
  "🚗 Transport & Driving",
  "🚌 Public Transportation",
  "🎓 School Education",
  "🏫 Higher Education",
  "💻 Digital Education & Literacy",
  "🧑‍🎓 Students & Scholarships",
  "🧑‍💻 Digital Government & e-Governance",
  "📱 Telecommunications & Internet",
  "🔬 Science, Technology & Innovation",
  "💡 Startups & Innovation",
  "🏢 Business & Entrepreneurship",
  "🏭 MSME & Industry",
  "🧑‍💼 Self-Employment",
  "🛍️ Trade & Markets",
  "🏗️ Infrastructure & Construction",
  "🏘️ Village & Community Development",
  "🧹 Cleanliness & Public Health",
  "🏛️ Local Government & Municipal Services",
  "🧑‍🌾 Rural Livelihoods & SHGs",
  "🧵 Handicrafts & Handlooms",
  "🎨 Arts, Culture & Heritage",
  "🏅 Sports & Athletes",
  "🧑‍🎤 Youth Development",
  "🪖 Defence & Armed Forces",
  "🎖️ Ex-Servicemen & Veterans",
  "👨‍👩‍👧 Family Welfare",
  "💍 Marriage Assistance",
  "🕊️ Widows & Single Women",
  "🧑‍⚖️ Victim & Vulnerable Person Support",
  "🏥 Nutrition & Food Security",
  "🍚 Food & Public Distribution",
  "🐝 Food Processing & Agro-Industry",
  "🌊 Coastal & Marine Communities",
  "🏔️ Tribal & Indigenous Communities",
  "🏜️ Border & Remote Area Development",
  "🧳 Tourism & Travel",
  "🛕 Pilgrimage & Religious Tourism",
  "🚂 Railways & Travel Assistance",
  "🌐 International & Overseas Assistance",
  "🧾 Taxes & Government Payments",
  "📊 Consumer Protection",
  "🛒 Consumer Affairs & Essential Commodities",
  "🧑‍⚕️ Public Health & Disease Prevention",
  "🧠 Mental & Social Wellbeing",
  "🧪 Research, Education & Fellowships",
  "🌞 Renewable Energy & Solar",
  "🏞️ Geographical & Regional Development",
  "🏛️ Heritage & Archaeology",
  "🐘 Wildlife & Biodiversity",
  "🌊 Water Resources & Irrigation",
  "🏗️ Mining & Natural Resources",
  "⚓ Ports & Maritime",
  "✈️ Aviation & Airports",
  "📦 Postal Services",
  "🏦 Financial Markets & Investor Protection",
  "🧑‍🔧 Occupational & Professional Welfare",
  "🧑‍🏫 Teachers & Education Professionals",
  "🏥 Healthcare Workers",
  "🧑‍🚒 Fire & Rescue Services",
  "🔐 Cybersecurity & Digital Safety",
  "📡 Information & Communication Services",
  "🗂️ Government Applications & Service Delivery",
  "🔄 Benefit Transfer & Payment Issues",
  "🧾 Eligibility & Scheme Discovery",
  "📑 Document Requirements & Verification",
  "📍 State & Local-Specific Schemes",
  "Others",
];

// Fallback category applied whenever no specific category is chosen.
export const OTHER_PROBLEM_CATEGORY = "Others";

// Resolves a stored/selected category to a safe display + submit value,
// always falling back to "Others" when nothing was chosen or the value
// doesn't match the known list.
export function resolveProblemCategory(value?: string | null): string {
  if (value && PROBLEM_CATEGORIES.includes(value)) {
    return value;
  }
  return OTHER_PROBLEM_CATEGORY;
}